### ISSUE TITLE
an install error

### ISSUE THREAD

**Issue by DogeWatch** [CIFASIS/QuickFuzz#64]
when I run stack install, there is an error:
Cabal-1.22.8.0: configure
Cabal-1.22.8.0: build
Progress: 1/189
--  While building package Cabal-1.22.8.0 using:
      /root/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.22.5.0_ghc-7.10.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.5.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure (-9) (THIS MAY INDICATE OUT OF MEMORY)
    Logs have been written to: /home/quickfuzz/QuickFuzz/.stack-work/logs/Cabal-1.22.8.0.log

and after this:
[19 of 81] Compiling Distribution.PackageDescription ( Distribution/PackageDescription.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/Distribution/PackageDescription.o )
the whole process finished, I do not know whether the installation is successful.

**Comment by gaa-cifasis** [comment]
Hi, 

sorry for the delay. This is a stack error caused by an out of memory of GHC. During the linking process, it can take a lot of memory to link and it can fail (specially if you are running other programs like a browser). You can try to re-run the same command (e.g. stack install --flag QuickFuzz:imgs) and sometimes you can avoid this error, otherwise you will need more memory to compile cabal. This kind of error is usual if you run it in small Linux virtual machine (or a VPS)

**Comment by gaa-cifasis** [comment]
Please test again with the refactored code and re-open if the compilation is failing.
